INSERT INTO credits VALUES ('ANair_MF', 'Anand S. Nair', 'PGS.', 'Anand S. Nair');
INSERT INTO credits VALUES ('APinhTOS', 'Armando Pinho', 'Computer code by Tomás Oliveira e Silva.', 'Armando Pinho [Tomás Oliveira e Silva]');
INSERT INTO credits VALUES ('A.Walker', 'Andrew John Walker', '', 'Andrew John Walker');
INSERT INTO credits VALUES ('AEWestrn', 'A. E. Western', '', 'A. E. Western');
INSERT INTO credits VALUES ('Andersen', 'Jens Kruse Andersen', '', 'Jens Kruse Andersen');
INSERT INTO credits VALUES ('ApplRssr', 'Kenneth I. Appel and J. Barkley Rosser', '', 'Appel and Rosser');
INSERT INTO credits VALUES ('ATeixTOS', 'António Teixera', 'Computer code by Tomás Oliveira e Silva.', 'António Teixera');
INSERT INTO credits VALUES ('Be.Nyman', 'Bertil Nyman', '', 'Bertil Nyman');
INSERT INTO credits VALUES ('Blnchtte', 'Gilles Blanchette', '', 'Gilles Blanchette');
INSERT INTO credits VALUES ('CBastTOS', 'Carlos Bastos', 'Computer code by Tomás Oliveira e Silva.', 'Carlos Bastos [Tomás Oliveira e Silva]');
INSERT INTO credits VALUES ('CKernTOS', 'Cristian Kern', 'Computer code by Tomás Oliveira e Silva.', 'Cristian Kern [Tomás Oliveira e Silva]');
INSERT INTO credits VALUES ('ColeStev', 'Steve Cole', 'PGS', 'Steve Cole');
INSERT INTO credits VALUES ('DanielH.', 'Daniel Hermle', '', 'Daniel Hermle');
INSERT INTO credits VALUES ('DBgh&FOH', 'D. Baugh and F. O’Hara', '', 'Baugh and O’Hara');
INSERT INTO credits VALUES ('DHLehmer', 'Derrick Henry Lehmer', '', 'Derrick Henry Lehmer');
INSERT INTO credits VALUES ('DonKnuth', 'Donald Ervin Knuth', '', 'Donald Ervin Knuth');
INSERT INTO credits VALUES ('Erickson', 'Eddie Erickson', '', 'Eddie Erickson');
INSERT INTO credits VALUES ('Euclid', 'Euclid', '', 'Euclid');
INSERT INTO credits VALUES ('Fougeron', 'Jim Fougeron', '', 'Jim Fougeron');
INSERT INTO credits VALUES ("GABandAR", 'F. J. Gruenberger, G. Armerding, and C. L. Baker (1959, 1961), and independently, Kenneth I. Appel and J. Barkley Rosser (1961)','', 'Gruenberger et.al, Appel and Rosser']);
INSERT INTO credits VALUES ('Gapcoin', 'The Gapcoin network, a Bitcoin derivative, employs a hashing algorithm which searches for prime gaps of high merit.', 'Jonnie Frey, developer.', 'The Gapcoin network');
INSERT INTO credits VALUES ('Glaisher', 'J. W. L. Glaisher', '', 'J. W. L. Glaisher');
INSERT INTO credits VALUES ('H.Dubner', 'Harvey Dubner', '', 'Harvey Dubner');
INSERT INTO credits VALUES ('HrzogTOS', 'Siegfried "Zig" Herzog', 'Computer code by Tomás Oliveira e Silva.', 'Siegfried "Zig" Herzog [Tomás Oliveira e Silva]');
INSERT INTO credits VALUES ('Jacobsen', 'Dana Jacobsen', 'running code using C and Perl', 'Dana Jacobsen');
INSERT INTO credits VALUES ('JamesFry', 'James Fry', '', 'James Fry');
INSERT INTO credits VALUES ('JdeGroot', 'Jeroen de Groot', '', 'Jeroen de Groot');
INSERT INTO credits VALUES ('JFNSTOeS', 'John Fettig and Nahil Sobh, NCSA', 'Computer code by Tomás Oliveira e Silva.', 'Fettig and Sobh [Tomás Oliveira e Silva]');
INSERT INTO credits VALUES ('JLGPardo', 'Jose Luis Gomez Pardo', '', 'Jose Luis Gomez Pardo');
INSERT INTO credits VALUES ('JRdrgTOS', 'João Manuel Rodrigues', 'Computer code by Tomás Oliveira e Silva.', 'João Manuel Rodrigues [Tomás Oliveira e Silva]');
INSERT INTO credits VALUES ('K.Conrow', 'Kenneth Conrow', '', 'Kenneth Conrow');
INSERT INTO credits VALUES ('KOGrndln', 'Kjell-Olav Grøndalen', '', 'Kjell-Olav Grøndalen');
INSERT INTO credits VALUES ('_Kokales', 'David Kokales', 'Also contributed deterministic primality proofs.', 'David Kokales');
INSERT INTO credits VALUES ('LLnhardy', 'Leif Leonhardy', '', 'Leif Leonhardy');
INSERT INTO credits VALUES ('LMorelli', 'Luigi Morelli', 'PGS', 'Luigi Morelli');
INSERT INTO credits VALUES ('LndrPrkn', 'L. J. Lander and Thomas R. Parkin', '', 'Lander and Parkin');
INSERT INTO credits VALUES ('M.Jansen', 'Michiel Jansen', '', 'Michiel Jansen');
INSERT INTO credits VALUES ('MJandJKA', 'Michiel Jansen and Jens Kruse Andersen', '', 'Jansen and Jens Kruse Andersen');
INSERT INTO credits VALUES ('MJPC&JKA', 'Michiel Jansen, Pierre Cami, and Jens Kruse Andersen', '', 'Jansen, Cami and Jens Kruse Andersen');
INSERT INTO credits VALUES ('ML.Brown', 'Milton L. Brown', '', 'Milton L. Brown');
INSERT INTO credits VALUES ('MrtnRaab', 'Martin Raab', '', 'Martin Raab');
INSERT INTO credits VALUES ('NicelyHD', 'Thomas R. Nicely', 'Computer code inspired by Harvey Dubner’s work.', 'Thomas R. Nicely [by Harvey Dubner]');
INSERT INTO credits VALUES ('NoAttrib', 'Anonymous contributors who do not wish attribution', '', 'Anonymous contributors');
INSERT INTO credits VALUES ('NuuKuosa', 'Nuutti Kuosa', '', 'Nuutti Kuosa');
INSERT INTO credits VALUES ('PardiTOS', 'Silvio Pardi', 'Computer code by Tomás Oliveira e Silva.', 'Silvio Pardi [Tomás Oliveira e Silva]');
INSERT INTO credits VALUES ('PDeGeest', 'Patrick De Geest', '', 'Patrick De Geest');
INSERT INTO credits VALUES ('PierCami', 'Pierre Cami', '', 'Pierre Cami');
INSERT INTO credits VALUES ('Pinho_MF', 'Carlos Eduardo Leal de Pinho', 'PGS', 'Carlos Eduardo Leal de Pinho');
INSERT INTO credits VALUES ('R.Athale', 'Rahul Ramesh Athale', '', 'Rahul Ramesh Athale');
INSERT INTO credits VALUES ('RFischer', 'Richard Fischer', '', 'Richard Fischer');
INSERT INTO credits VALUES ('Ritschel', 'Thomas Ritschel', 'PGS', 'Thomas Ritschel');
INSERT INTO credits VALUES ('RobSmith', 'Robert W. Smith', 'Coordinator, PGS. Some results contributed after 2014 employ Perl code written by Dana Jacobsen.', 'Robert W. Smith [Dana Jacobsen');
INSERT INTO credits VALUES ('Rosnthal', 'Hans Rosenthal', '', 'Hans Rosenthal');
INSERT INTO credits VALUES ('RosntlJA', 'Hans Rosenthal', 'Computer code by Jens Kruse Andersen.', 'Hans Rosenthal [Jens Kruse Andersen]');
INSERT INTO credits VALUES ('RosntlJF', 'Hans Rosenthal', 'Computer code by Jim Fougeron.', 'Hans Rosenthal [Jim Fougeron]');
INSERT INTO credits VALUES ('RP.Brent', 'Richard P. Brent', '', 'Richard P. Brent');
INSERT INTO credits VALUES ('Shepherd', 'Rick L. Shepherd', '', 'Rick L. Shepherd');
INSERT INTO credits VALUES ('Spielaur', 'Helmut Spielauer', '', 'Helmut Spielauer');
INSERT INTO credits VALUES ('TAlmFMJA', 'Torbjörn Alm', 'Computer code by Jens Kruse Andersen. Deterministic primality proofs by François Morain.', 'Torbjörn Alm [Jens Kruse Andersen]');
INSERT INTO credits VALUES ('T.Hadley', 'Thomas Hadley', '', 'Thomas Hadley');
INSERT INTO credits VALUES ('TOeSilva', 'Tomás Oliveira e Silva', '', 'Tomás Oliveira e Silva');
INSERT INTO credits VALUES ('Toni_Key', 'Antonio Key', 'Using Perl codes developed by Dana Jacobsen.', 'Antonio Key [Dana Jacobsen]');
INSERT INTO credits VALUES ('TorAlmJA', 'Torbjörn Alm', 'Computer code by Jens Kruse Andersen.', 'Torbjörn Alm [Jens Kruse Andersen]');
INSERT INTO credits VALUES ('TRNicely', 'Thomas R. Nicely', '', 'Thomas R. Nicely');
INSERT INTO credits VALUES ('Weslwski', 'Arkadiusz Wesołowski', '', 'Arkadiusz Wesołowski');
INSERT INTO credits VALUES ('Yng&Ptlr', 'Jeff Young and Aaron Potler', '', 'Jeff Young and Aaron Potler');
INSERT INTO credits VALUES ('YPPauloR', 'Jeff Young and Aaron Potler, as reported by Paulo Ribenboim', '', 'Jeff Young and Aaron Potler [by Paulo Ribenboim]');
